name: Norm

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Compiling using GCC
      run: make

    - name: Compiling using Clang
      run: make
